# Generated by Django 5.0.14 on 2025-06-25 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ciudades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_ciudades", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
                "db_table": "ciudades",
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_departamento", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "departamento",
            },
        ),
        migrations.CreateModel(
            name="DepartamentoPais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_departamento", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DeparamentoPais",
                "verbose_name_plural": "DepartamentosPais",
                "db_table": "deparamentopais",
            },
        ),
        migrations.CreateModel(
            name="Empresas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_empresa", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
            },
        ),
        migrations.CreateModel(
            name="Inventariotelefonos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "nombretelefono",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "correlativo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estado", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "estadotelefono",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("valortotal", models.FloatField(blank=True, null=True)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario Telefono",
                "verbose_name_plural": "Inventario Telefonos",
                "db_table": "inventariotelefono",
            },
        ),
        migrations.CreateModel(
            name="Jefes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("codigo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "identidadjefe",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("nombrejefe", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jefes",
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jefes",
                        to="Reclutamiento.empresas",
                    ),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jefe",
                "verbose_name_plural": "Jefes",
                "db_table": "jefes",
            },
        ),
        migrations.CreateModel(
            name="Colaboradores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "codigocolaborador",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nombrecolaborador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dni", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colaboradores",
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colaboradores",
                        to="Reclutamiento.empresas",
                    ),
                ),
                (
                    "jefe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colaboradores",
                        to="Reclutamiento.jefes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
                "db_table": "colaboradores",
            },
        ),
        migrations.CreateModel(
            name="Cesantias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "correlativo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_inicial", models.DateField(blank=True, null=True)),
                ("fecha_final", models.DateField(blank=True, null=True)),
                ("año", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sueldo_actual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cesantia_actual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cesantia_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fecha_extencion", models.DateField(blank=True, null=True)),
                (
                    "porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("n_cheke", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cesantias_empleado",
                        to="Reclutamiento.colaboradores",
                    ),
                ),
                (
                    "autoriza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="autoriza_cesantias",
                        to="Reclutamiento.jefes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cesantias",
                "verbose_name_plural": "Cesantias",
                "db_table": "cesantias",
            },
        ),
        migrations.CreateModel(
            name="MedioReclutamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_medio_de_reclutamiento", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medio de Reclutamiento",
                "verbose_name_plural": "Medios de Reclutamiento",
                "db_table": "medio_de_reclutamiento",
            },
        ),
        migrations.CreateModel(
            name="BolsaEmpleos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("dni", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "nombre_candidato",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono2", models.CharField(blank=True, max_length=20, null=True)),
                ("estado", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "estadocivil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nhijos", models.IntegerField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mediomovilizacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experiencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombredocumento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.ciudades",
                    ),
                ),
                (
                    "medio_reclutamiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.medioreclutamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bolsa de Empleo",
                "verbose_name_plural": "Bolsa de Empleos",
                "db_table": "bolsa_empleos",
            },
        ),
        migrations.CreateModel(
            name="Modo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_modo", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modo",
                "verbose_name_plural": "Modos",
                "db_table": "modo",
            },
        ),
        migrations.CreateModel(
            name="Motivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_motivo", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo",
                "verbose_name_plural": "Motivos",
                "db_table": "motivo",
            },
        ),
        migrations.CreateModel(
            name="MunicipioPais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_municipio", models.CharField(max_length=255)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departamentos_pais",
                        to="Reclutamiento.departamentopais",
                    ),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MunicipioPais",
                "verbose_name_plural": "MunicipiosMunicipioPaisPais",
                "db_table": "municipiospais",
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_pais", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pais",
                "verbose_name_plural": "Paises",
                "db_table": "pais",
            },
        ),
        migrations.AddField(
            model_name="departamentopais",
            name="pais",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pais_departamentohonduras",
                to="Reclutamiento.pais",
            ),
        ),
        migrations.CreateModel(
            name="PerfilesPuestos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_perfil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cargo_que_le_reportan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "educacion_universitario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postgrado_especializaciones",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "formacion_complementaria",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("idiomas", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nivel_idioma",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anos_experiencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pensamiento_estrategico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enfoque_al_cliente",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "planificacion_y_organizacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comunicacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "orientacion_al_logro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mision_cargo", models.TextField(blank=True, null=True)),
                (
                    "ruta_organigrama",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nombre_organigrama",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("residir_en_area", models.BooleanField(default=False)),
                ("hora_entrada", models.TimeField(blank=True, null=True)),
                ("hora_salida", models.TimeField(blank=True, null=True)),
                ("otros_considere", models.TextField(blank=True, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.empresas",
                    ),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "perfiles_puestos",
            },
        ),
        migrations.CreateModel(
            name="PerfilDificultades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retos",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_dificultades",
            },
        ),
        migrations.CreateModel(
            name="MaterialEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiales_equipos",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_materiales",
            },
        ),
        migrations.CreateModel(
            name="IndicadorPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_indicadores",
            },
        ),
        migrations.CreateModel(
            name="FuncionCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funcion", models.CharField(max_length=255)),
                ("periodicidad", models.CharField(max_length=50)),
                ("importancia", models.CharField(max_length=1)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funciones",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_funcionarcargo",
            },
        ),
        migrations.CreateModel(
            name="BeneficioPromaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficios_promaco",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_beneficios",
            },
        ),
        migrations.CreateModel(
            name="PlanCompensacionPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_de_compensacion",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_compensacion",
            },
        ),
        migrations.CreateModel(
            name="Prioridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_prioridad", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prioridad",
                "verbose_name_plural": "Prioridades",
                "db_table": "prioridad",
            },
        ),
        migrations.CreateModel(
            name="Puestos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_puestos", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto",
                "verbose_name_plural": "Puestos",
                "db_table": "puestos",
            },
        ),
        migrations.CreateModel(
            name="PuestoAspira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reclutamiento.bolsaempleos",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reclutamiento.puestos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto al que aspira",
                "verbose_name_plural": "Puestos a los que aspira",
                "db_table": "puesto_aspira",
                "unique_together": {("candidato", "puesto")},
            },
        ),
        migrations.CreateModel(
            name="PuestoAplica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reclutamiento.bolsaempleos",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reclutamiento.puestos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto al que aplica",
                "verbose_name_plural": "Puestos a los que aplica",
                "db_table": "puesto_aplica",
                "unique_together": {("candidato", "puesto")},
            },
        ),
        migrations.AddField(
            model_name="perfilespuestos",
            name="cargo_al_que_reporta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jefes_directos",
                to="Reclutamiento.puestos",
            ),
        ),
        migrations.AddField(
            model_name="perfilespuestos",
            name="nombre_cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nombre_cargo",
                to="Reclutamiento.puestos",
            ),
        ),
        migrations.AddField(
            model_name="jefes",
            name="puesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="puestojefes",
                to="Reclutamiento.puestos",
            ),
        ),
        migrations.AddField(
            model_name="colaboradores",
            name="puesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="puestocolaborador",
                to="Reclutamiento.puestos",
            ),
        ),
        migrations.CreateModel(
            name="CargoReporta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos_reporta",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reclutamiento.puestos",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_cargoreporta",
            },
        ),
        migrations.AddField(
            model_name="bolsaempleos",
            name="puestosaplica",
            field=models.ManyToManyField(
                blank=True,
                related_name="aplicantes",
                through="Reclutamiento.PuestoAplica",
                to="Reclutamiento.puestos",
            ),
        ),
        migrations.AddField(
            model_name="bolsaempleos",
            name="puestosaspira",
            field=models.ManyToManyField(
                blank=True,
                related_name="aspirantes",
                through="Reclutamiento.PuestoAspira",
                to="Reclutamiento.puestos",
            ),
        ),
        migrations.CreateModel(
            name="Spicosmart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nivel", models.CharField(max_length=255)),
                ("nombre_prueba", models.CharField(max_length=255)),
                ("prueba_mide", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Psicosmart",
                "verbose_name_plural": "Psicosmarts",
                "db_table": "psicosmart",
            },
        ),
        migrations.AddField(
            model_name="perfilespuestos",
            name="nivel_psicosmart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Reclutamiento.spicosmart",
            ),
        ),
        migrations.CreateModel(
            name="SpicosmartAsignadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pruebas_psicosmart",
                        to="Reclutamiento.perfilespuestos",
                    ),
                ),
                (
                    "prueba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reclutamiento.spicosmart",
                    ),
                ),
            ],
            options={
                "db_table": "perfilpuesto_psicosmartasignadas",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_sucursal", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "db_table": "sucursal",
            },
        ),
        migrations.AddField(
            model_name="jefes",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jefes",
                to="Reclutamiento.sucursal",
            ),
        ),
        migrations.CreateModel(
            name="ContratacionEmpleadosmulti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_contratacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nombre1", models.CharField(blank=True, max_length=50, null=True)),
                ("nombre2", models.CharField(blank=True, max_length=50, null=True)),
                ("apellido1", models.CharField(blank=True, max_length=50, null=True)),
                ("apellido2", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("dni", models.CharField(blank=True, max_length=13, null=True)),
                ("genero", models.CharField(blank=True, max_length=25, null=True)),
                ("direccionexacta", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "estado_civil",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "profecion_oficio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ultimo_grado_estudio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("puestos", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("salario", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nombre_emergencia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parentesco", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "telefonoemergencia",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("enfermedad", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nombre_beneficiario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dni_beneficiario",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "parentesco_beneficiario",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("porcentaje", models.IntegerField(blank=True, null=True)),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombreimagen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.municipiopais",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contratacion de Empleado Multi",
                "verbose_name_plural": "Contrataciones de Empleados Multi",
                "db_table": "contratacion_empleados_multi",
            },
        ),
        migrations.AddField(
            model_name="colaboradores",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colaboradores",
                to="Reclutamiento.sucursal",
            ),
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_tipo_de_contrato", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Contrato",
                "verbose_name_plural": "Tipos de Contrato",
                "db_table": "tipo_de_contrato",
            },
        ),
        migrations.CreateModel(
            name="Requisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "salario_base",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fechaRecepcion", models.DateTimeField(blank=True, null=True)),
                ("plan_de_compensacion", models.JSONField(blank=True, null=True)),
                ("montos", models.JSONField(blank=True, null=True)),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                (
                    "centrocostos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("puestonuevo", models.BooleanField(default=False)),
                ("incapacidad", models.BooleanField(default=False)),
                ("reemplazo", models.BooleanField(default=False)),
                (
                    "tiempoprimercontrato",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("motivo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombrereemplazar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("funciones_cargo", models.TextField(blank=True, null=True)),
                (
                    "formacionacademica",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("habilidadesferreteras", models.JSONField(blank=True, null=True)),
                ("habilidadesinformaticas", models.JSONField(blank=True, null=True)),
                ("habilidadespersonales", models.JSONField(blank=True, null=True)),
                ("habilidadesanaliticas", models.JSONField(blank=True, null=True)),
                ("materialesequipo", models.JSONField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisa",
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="puesto",
                        to="Reclutamiento.puestos",
                    ),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisa",
                        to="Reclutamiento.sucursal",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisa",
                        to="Reclutamiento.tipocontrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisa",
                "verbose_name_plural": "Requisas",
                "db_table": "requisa",
            },
        ),
        migrations.CreateModel(
            name="Unidad_Negocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("nombre_unidad_de_negocio", models.CharField(max_length=255)),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Negocio",
                "verbose_name_plural": "Unidades de Negocio",
                "db_table": "unidad_de_negocio",
            },
        ),
        migrations.CreateModel(
            name="Telefonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                (
                    "correlativo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("dni", models.CharField(blank=True, max_length=13, null=True)),
                ("fechaextravio", models.DateField(blank=True, null=True)),
                (
                    "nombretelefono",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("MEI", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lineatelefonica",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("caracter", models.CharField(blank=True, max_length=20, null=True)),
                ("valor", models.FloatField(blank=True, null=True)),
                ("tiempopago", models.IntegerField(blank=True, null=True)),
                ("quinsena", models.FloatField(blank=True, null=True)),
                (
                    "estadotelefono",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "asignacionnueva",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("valortotal", models.FloatField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("valorquincena", models.FloatField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telefonia",
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidad_de_negocio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telefonia",
                        to="Reclutamiento.unidad_negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telefonia",
                "verbose_name_plural": "Telefonias",
                "db_table": "telefonia",
            },
        ),
        migrations.AddField(
            model_name="jefes",
            name="unidad_de_negocio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jefes",
                to="Reclutamiento.unidad_negocio",
            ),
        ),
        migrations.CreateModel(
            name="ControlDeTiempo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("unid_puesto", models.CharField(max_length=255)),
                ("tiempo", models.IntegerField()),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles_tiempo",
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "puestos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles_tiempo",
                        to="Reclutamiento.puestos",
                    ),
                ),
                (
                    "unidad_de_negocio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controles_tiempo",
                        to="Reclutamiento.unidad_negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Tiempo",
                "verbose_name_plural": "Controles de Tiempo",
                "db_table": "control_de_tiempo",
            },
        ),
        migrations.CreateModel(
            name="ControlDePlazas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("año", models.IntegerField(blank=True, null=True)),
                ("mes_corte", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mes_solicitud",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nombre_reemplazo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unidad_puesto",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tiempo_cobertura", models.IntegerField(blank=True, null=True)),
                ("fecha_solicitud", models.DateField(blank=True, null=True)),
                ("fecha_inicio_busqueda", models.DateField(blank=True, null=True)),
                ("fecha_cobertura", models.DateField(blank=True, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                (
                    "tiempo_efectivo_cobertura",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tiempo_efectivo_fecha_ingreso",
                    models.IntegerField(blank=True, null=True),
                ),
                ("fecha_limite_cobertura", models.DateField(blank=True, null=True)),
                ("tiempo_disponible", models.IntegerField(blank=True, null=True)),
                ("estatus", models.CharField(blank=True, max_length=20, null=True)),
                ("cantidad_solicitada", models.IntegerField(blank=True, null=True)),
                ("cantidad_cubierta", models.IntegerField(blank=True, null=True)),
                (
                    "fuente_reclutamiento",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nombre_contratado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dni", models.CharField(blank=True, max_length=13, null=True)),
                ("genero", models.CharField(blank=True, max_length=1, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "salario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "combustible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "depreciacion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "comision",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bono",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hospedaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombreimagen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ruta1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombreimagen1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.empresas",
                    ),
                ),
                (
                    "medio_reclutamiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.medioreclutamiento",
                    ),
                ),
                (
                    "modo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.modo",
                    ),
                ),
                (
                    "motivo_ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.motivo",
                    ),
                ),
                (
                    "prioridad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.prioridad",
                    ),
                ),
                (
                    "puestos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.puestos",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.sucursal",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.tipocontrato",
                    ),
                ),
                (
                    "unidad_de_negocio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_de_plazas",
                        to="Reclutamiento.unidad_negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Plazas",
                "verbose_name_plural": "Controles de Plazas",
                "db_table": "control_de_plazas",
            },
        ),
        migrations.CreateModel(
            name="ContratacionEmpleados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_contratacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("nombre1", models.CharField(blank=True, max_length=50, null=True)),
                ("nombre2", models.CharField(blank=True, max_length=50, null=True)),
                ("apellido1", models.CharField(blank=True, max_length=50, null=True)),
                ("apellido2", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=25, null=True)),
                ("direccionexacta", models.TextField(blank=True, null=True)),
                ("dni", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "estado_civil",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("hijos", models.BooleanField(default=False)),
                (
                    "profecion_oficio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "nombre1_emergencia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parentesco1", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "telefonoemergencia1",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nombre2_emergencia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parentesco2", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "telefonoemergencia2",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nivel_educativo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ultimo_grado_estudio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ultimogradodetalle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("padecimiento", models.BooleanField(default=False)),
                (
                    "detalle_enfermedad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("salario", models.CharField(blank=True, max_length=50, null=True)),
                ("comision", models.CharField(blank=True, max_length=50, null=True)),
                ("bofa", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("direccionempresa", models.TextField(blank=True, null=True)),
                (
                    "telefono_empresa",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "nombre_beneficiario",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dni_beneficiario",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "parentesco_beneficiario",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("porcentaje", models.IntegerField(blank=True, null=True)),
                ("ruta", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombreimagen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usuario_creo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_creo_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_modifico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_modifico_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento_empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.departamento",
                    ),
                ),
                (
                    "nombre_empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.empresas",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.municipiopais",
                    ),
                ),
                (
                    "puestos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.puestos",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.sucursal",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.tipocontrato",
                    ),
                ),
                (
                    "unidad_de_negocio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Reclutamiento.unidad_negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contratacion de Empleado",
                "verbose_name_plural": "Contrataciones de Empleados",
                "db_table": "contratacion_empleados",
            },
        ),
        migrations.AddField(
            model_name="colaboradores",
            name="unidad_de_negocio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colaboradores",
                to="Reclutamiento.unidad_negocio",
            ),
        ),
    ]
