# Generated by Django 5.0.14 on 2025-06-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reclutamiento", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilespuestos",
            name="cargo_que_le_reportan",
        ),
    ]
