# Generated by Django 5.0.14 on 2025-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reclutamiento", "0002_remove_perfilespuestos_cargo_que_le_reportan"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilespuestos",
            name="equipo_pesado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="perfilespuestos",
            name="montacargas",
            field=models.BooleanField(default=False),
        ),
    ]
